apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crudgo
  template:
    metadata:
      labels:
        app: crudgo
    spec:
      containers:
        - name: crudgo
          image: osmait/crudgo:latest
          ports:
            - containerPort: 8080
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8080"
