# Establece la imagen base para Go
FROM golang:1.20-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos necesarios
COPY . .

# Compila la aplicación
RUN go build -o crud ./cmd
ENV HOST 0.0.0.0
ENV PORT 8080

# Expone el puerto en el que se ejecutará la aplicación
EXPOSE 8080

# Establece el comando para iniciar la aplicación
CMD ["./crud"]
